# Generated by Django 3.1.2 on 2020-10-15 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20201015_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFindings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('translation', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.report')),
            ],
        ),
    ]
