FROM python:3.8.2

WORKDIR /app

RUN python -m pip install -U pip
COPY . .
RUN pip install -r requirements.txt
CMD chown app /home/app/scanslated/portal/static && chown app /home/app/scanslated/portal/media